{{- if and .Values.cloudTunnel.enabled .Values.cloudTunnel.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "espwifi.io.fullname" . }}-cloudtunnel
  labels:
    {{- include "espwifi.io.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloudtunnel
  {{- with .Values.cloudTunnel.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.cloudTunnel.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.cloudTunnel.ingress.tls }}
  tls:
    {{- range .Values.cloudTunnel.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.cloudTunnel.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "espwifi.io.fullname" $ }}-cloudtunnel
                port:
                  number: {{ $.Values.cloudTunnel.service.port }}
          {{- end }}
    {{- end }}
{{- end }}


